### ISSUE TITLE
Incompatible with Immersive Portals

### ISSUE THREAD

**Issue by el0c** [Celibistrial/freelook#9]
When the mod is installed alongside Immersive portals, pressing the free look key works but you are unable to move your mouse around. 

Tested with:
Minecraft 1.18.1
Fabric Loader 0.12.12
Fabric API 0.45.0
Freelook 1.1.0
Immersive Portals 1.1.7

Not sure if there's anything you can do from your end, or if a separate issue needs to be created with the Immersive Portals team.

**Comment by Celibistrial** [comment]
Hmm, I think it's because the immersive portal makes a separate camera (don't quote me on this) so changing perspective works but the freelook mod changes the wrong camera's rotation.
Pretty sure I can fix this but if the immersive portal mod does make a separate camera it would be incompatible with many more mods, so might be better for them to just use the default camera.
 
I will try fixing it tho.

**Comment by Celibistrial** [comment]
Ok after looking into this further I cannot fix it, so ill just mark these 2 mods incompatible
